### ISSUE TITLE
[SUGESTION] Isotopes and radioactivity

### ISSUE THREAD

**Issue by JukoiDev** [SmashingMods/ChemLib#15]
These would be inevitable.

**Comment by OniyaMCD** [comment]
Why?  What would you intend for this to add to gameplay?

**Comment by MasterEnderman** [comment]
Radioactivity and some things related to that, will be part of another addon mod and not chemlib. Currently there're no plans to add isotopes or other particles. Maybe we'll take a look at those in the future.

**Comment by JukoiDev** [comment]
thats sound alright
