### ISSUE TITLE
Licensing Ask

### ISSUE THREAD

**Issue by Mg138** [SmashingMods/ChemLib#5]
What is the license for the code (and maybe the assets)?
I'm planning on porting the mod to Fabric + using Kotlin, and most of the code will have the same signature and naming. What is the license for your stuff? What should I add as Author?

**Comment by DracoNocte** [comment]
Hello @Mg138!
According to the mod page on [CurseForge](https://www.curseforge.com/minecraft/mc-mods/chemlib), the license seems to be MIT.
Since I'm not part of the dev team, I recommend that you wait for an official answer or that you contact directly the mod owner concerning that matter.

**Comment by Dark-Arcana** [comment]
I would strongly recommend against any porting right now as this will be greatly rewritten soon and may even include a fabric release.

**Comment by Mg138** [comment]
it's already ported, rewritten as you may expect, and using some datagen fuckery
it's under MIT iirc

**Comment by Dark-Arcana** [comment]
Can you link it for me?

**Comment by Mg138** [comment]
https://github.com/Mg138/ChemLibFabric

**Comment by Mg138** [comment]
Oh, I also discarded a few features, as they're either broken or so badly written I can't make sense of it.

**Comment by Dark-Arcana** [comment]
> Oh, I also discarded a few features, as they're either broken or so badly written I can't make sense of it. But the chemicals are all there

This is true. I'm currently completely rewriting Alchemistry because it's in a poor state. I will be rewriting ChemLib too. When I do start that rewrite, I am indeed changing the license from MIT to something slightly more restrictive. Open source still of course.

**Comment by Mg138** [comment]
Good luck, I could give a hand if you'd like.

**Comment by Dark-Arcana** [comment]
ChemLib is currently licensed "All Right Reserved" which means technically you can't make a modified copy or distribute it. I'm looking into changing the licenses to make that possible, but with a caveat about publishing to anywhere (CurseForge). I would only want high quality code and someone I can work with to be able to publish. For now, I'm going to decide that there shouldn't be any publicly distributed forks of ChemLib. I just wanted to let you know.

If you want to work together on a Fabric port, join the Discord.

**Comment by Mg138** [comment]
Eh.. Where's the Discord?

**Comment by Mg138** [comment]
Nvm, googled the project Smashing Mods and found it
